scrollConfig: |
  {
    "addresses": [
      {
        "rpc_url": "https://alien-flashy-arm.ethereum-sepolia.quiknode.pro/2aeb75414e5ee0e930b64c2e7feff59efb537f30",
        "min_balance_ether": "10",
        "address": "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
        "name": "L1_COMMIT_SENDER"
      },
      {
        "rpc_url": "https://alien-flashy-arm.ethereum-sepolia.quiknode.pro/2aeb75414e5ee0e930b64c2e7feff59efb537f30",
        "min_balance_ether": "10",
        "address": "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
        "name": "L1_FINALIZE_SENDER"
      },
      {
        "rpc_url": "https://alien-flashy-arm.ethereum-sepolia.quiknode.pro/2aeb75414e5ee0e930b64c2e7feff59efb537f30",
        "min_balance_ether": "1.1",
        "address": "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
        "name": "L1_GAS_ORACLE_SENDER"
      },
      {
        "rpc_url": "https://alien-flashy-arm.ethereum-sepolia.quiknode.pro/2aeb75414e5ee0e930b64c2e7feff59efb537f30",
        "min_balance_ether": "0",
        "address": "0x0000000000000000000000000000000000000001",
        "name": "L1_SCROLL_FEE_VAULT"
      },
      {
        "rpc_url": "http://l2-sequencer:8545",
        "min_balance_ether": "1.1",
        "address": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
        "name": "L2_GAS_ORACLE_SENDER"
      },
      {
        "rpc_url": "http://l2-sequencer:8545",
        "min_balance_ether": "0",
        "address": "0x5300000000000000000000000000000000000005",
        "name": "L2_TX_FEE_VAULT"
      }
    ],
    "JOB_INTERVAL_SECS": 60,
    "BIND_PORT": 8080
  }
