scrollConfig: |
  {
    "prover_manager": {
      "provers_per_session": 1,
      "session_attempts": 100,
      "chunk_collection_time_sec": 360,
      "batch_collection_time_sec": 180,
      "bundle_collection_time_sec": 60,
      "verifier": {
        "mock_mode": false,
        "low_version_circuit": {
          "params_path": "/verifier/params",
          "assets_path": "/verifier/assets/lo",
          "fork_name": "darwin",
          "min_prover_version": "v4.4.43"
        },
        "high_version_circuit": {
          "params_path": "/verifier/params",
          "assets_path": "/verifier/assets/hi",
          "fork_name": "darwinV2",
          "min_prover_version": "v4.4.56"
        }
      },
      "max_verifier_workers": 4,
      "min_prover_version": "v4.3.41"
    },
    "db": {
      "driver_name": "postgres",
      "dsn": "",
      "maxOpenNum": 200,
      "maxIdleNum": 20
    },
    "l2": {
      "chain_id": 221122
    },
    "auth": {
      "secret": "e788b62d39254928a821ac1c76b274a8c835aa1e20ecfb6f50eb10e87847de44",
      "challenge_expire_duration_sec": 10,
      "login_expire_duration_sec": 3600
    }
  }
