scrollConfig: |
  REACT_APP_ETH_SYMBOL = "ETH"
  REACT_APP_BASE_CHAIN = "Ethereum"
  REACT_APP_ROLLUP = "Scroll SDK"
  REACT_APP_CHAIN_ID_L1 = "11155111"
  REACT_APP_CHAIN_ID_L2 = "221122"
  REACT_APP_CONNECT_WALLET_PROJECT_ID = "14efbaafcf5232a47d93a68229b71028"
  
  REACT_APP_EXTERNAL_RPC_URI_L1 = "http://l1-devnet.scrollsdk"
  REACT_APP_EXTERNAL_RPC_URI_L2 = "http://l2-rpc.scrollsdk"
  REACT_APP_BRIDGE_API_URI = "http://bridge-history-api.scrollsdk/api"
  REACT_APP_ROLLUPSCAN_API_URI = "http://rollup-explorer-backend.scrollsdk/api"
  REACT_APP_EXTERNAL_EXPLORER_URI_L1 = "http://l1-explorer.scrollsdk"
  REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "http://blockscout.scrollsdk"
  ADMIN_SYSTEM_DASHBOARD_URI = "http://admin-system-dashboard.scrollsdk"
  GRAFANA_URI = "http://grafana.scrollsdk"
  
  REACT_APP_L1_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0xCD832C95AabA0d2f50d7567b21A43a5d93a932b0"
  REACT_APP_L1_ETH_GATEWAY_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
  REACT_APP_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"
  REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "0xFeA8784A9f31f6f6895e65B65eE63fC85d324F5F"
  REACT_APP_L1_MESSAGE_QUEUE = "0x74E69415630e35631eb0D2199AF6De5e010B58B2"
  REACT_APP_L1_MESSAGE_QUEUE_WITH_GAS_PRICE_ORACLE = "0x74E69415630e35631eb0D2199AF6De5e010B58B2"
  REACT_APP_L1_SCROLL_MESSENGER = "0xf5a927Ea81032Dbe3921424E18Ad81E3680C86ac"
  REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x8c7fff50e219E2795ccCF188bD9728d0C4009c1b"
  REACT_APP_L1_WETH_GATEWAY_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
  REACT_APP_SCROLL_CHAIN = "0x3177d80e33919312244Fbbd70E4aA95eBB27070a"
  REACT_APP_L1_GAS_TOKEN_GATEWAY = "0xD287a0Cf91D27E876BeAF0977093eB47d6Cc4381"
  REACT_APP_L1_WRAPPED_TOKEN_GATEWAY = "0xA3d3011C108816B3eE0468c04aC61036bA06Fb6e"
  REACT_APP_L1_GAS_TOKEN_ADDR = "0x8258c70A41de87A98d7fAD2BbF7c1009845a8A1D"
  REACT_APP_L1_WETH_ADDR = "0x0e8fEBf2fa907513d10B433c01B5F444A5c113bF"
  
  REACT_APP_L2_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0x1AE0E1685fD6b34382D10eE90C7d7e2B2D647A09"
  REACT_APP_L2_ETH_GATEWAY_PROXY_ADDR = "0xAd7de4158e155fBfDeA9C20aC682351C6e78a58f"
  REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0xA26fEdaeA13041f7bc6c36774c03265b3d26c5ac"
  REACT_APP_L2_SCROLL_MESSENGER = "0xd36B5A075cF7d22F46aa3E1C89d21d0C5cc16ebF"
  REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x0C2e35775Bd36d28A96da0D31C933A9C4773cE10"
  REACT_APP_L2_WETH_GATEWAY_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
  
  REACT_APP_L1_USDC_GATEWAY_PROXY_ADDR = ""
  REACT_APP_L2_USDC_GATEWAY_PROXY_ADDR = ""
  REACT_APP_L1_DAI_GATEWAY_PROXY_ADDR = ""
  REACT_APP_L2_DAI_GATEWAY_PROXY_ADDR = ""
  REACT_APP_L1_LIDO_GATEWAY_PROXY_ADDR = ""
  REACT_APP_L2_LIDO_GATEWAY_PROXY_ADDR = ""
  REACT_APP_L1_PUFFER_GATEWAY_PROXY_ADDR = ""
  REACT_APP_L2_PUFFER_GATEWAY_PROXY_ADDR = ""
  
  REACT_APP_SCROLL_ORIGINS_NFT = ""
  REACT_APP_SCROLL_ORIGINS_NFT_V2 = ""
  REACT_APP_L1_BATCH_BRIDGE_GATEWAY_PROXY_ADDR = ""
