scrollConfig: |
  {
    "l1_config": {
      "endpoint": "https://alien-flashy-arm.ethereum-sepolia.quiknode.pro/2aeb75414e5ee0e930b64c2e7feff59efb537f30",
      "start_height": 0,
      "relayer_config": {
        "gas_price_oracle_contract_address": "0x5300000000000000000000000000000000000002",
        "sender_config": {
          "endpoint": "http://l2-sequencer:8545",
          "escalate_blocks": 100,
          "escalate_multiple_num": 11,
          "escalate_multiple_den": 10,
          "min_gas_tip": 1,
          "max_gas_price": 10000000000000,
          "tx_type": "DynamicFeeTx",
          "check_pending_time": 3,
          "confirmations": "0x0"
        },
        "gas_oracle_config": {
          "min_gas_price": 0,
          "gas_price_diff": 50000,
          "l1_base_fee_weight": 0.086,
          "l1_blob_base_fee_weight": 0.030,
          "check_committed_batches_window_minutes": 5,
          "l1_base_fee_default": 15000000000,
          "l1_blob_base_fee_default": 1,
          "alternative_gas_token_config": {
            "enabled": false,
            "mode": "Fixed",
            "fixed_exchange_rate": 0.001,
            "token_symbol_pair": ""
          }
        },
        "gas_oracle_sender_signer_config": {
          "signer_type": "PrivateKey",
          "private_key_signer_config": {
            "private_key": "1313131313131313131313131313131313131313131313131313131313131313"
          }
        }
      }
    },
    "l2_config": {
      "confirmations": "0x10",
      "endpoint": "http://l2-sequencer:8545",
      "l2_message_queue_address": "0x5300000000000000000000000000000000000000",
      "relayer_config": {
        "rollup_contract_address": "0x3177d80e33919312244Fbbd70E4aA95eBB27070a",
        "gas_price_oracle_contract_address": "0x74E69415630e35631eb0D2199AF6De5e010B58B2",
        "sender_config": {
          "endpoint": "https://alien-flashy-arm.ethereum-sepolia.quiknode.pro/2aeb75414e5ee0e930b64c2e7feff59efb537f30",
          "escalate_blocks": 4,
          "escalate_multiple_num": 12,
          "escalate_multiple_den": 10,
          "min_gas_tip": 100000000,
          "max_gas_price": 200000000000,
          "max_blob_gas_price": 200000000000,
          "tx_type": "DynamicFeeTx",
          "check_pending_time": 10,
          "confirmations": "0x0",
          "max_pending_blob_txs": 3
        },
        "gas_oracle_config": {
          "min_gas_price": 0,
          "gas_price_diff": 50000,
          "alternative_gas_token_config": {
            "enabled": false,
            "mode": "Fixed",
            "fixed_exchange_rate": 0.001,
            "token_symbol_pair": ""
          }
        },
        "chain_monitor": {
          "enabled": true,
          "timeout": 3,
          "try_times": 5,
          "base_url": "http://chain-monitor:8080"
        },
        "enable_test_env_bypass_features": false,
        "finalize_batch_without_proof_timeout_sec": 300,
        "finalize_bundle_without_proof_timeout_sec": 300,
        "gas_oracle_sender_signer_config": {
          "signer_type": "PrivateKey",
          "private_key_signer_config": {
            "private_key": "1313131313131313131313131313131313131313131313131313131313131313"
          }
        },
        "commit_sender_signer_config": {
          "signer_type": "PrivateKey",
          "private_key_signer_config": {
            "private_key": "1414141414141414141414141414141414141414141414141414141414141414"
          }
        },
        "finalize_sender_signer_config": {
          "signer_type": "PrivateKey",
          "private_key_signer_config": {
            "private_key": "1515151515151515151515151515151515151515151515151515151515151515"
          }
        },
        "l1_commit_gas_limit_multiplier": 1.2
      },
      "chunk_proposer_config": {
        "propose_interval_milliseconds": 100,
        "max_block_num_per_chunk": 100,
        "max_tx_num_per_chunk": 100,
        "max_l1_commit_gas_per_chunk": 5000000,
        "max_l1_commit_calldata_size_per_chunk": 110000,
        "chunk_timeout_sec": 2700,
        "max_row_consumption_per_chunk": 1000000,
        "gas_cost_increase_multiplier": 1.2,
        "max_uncompressed_batch_bytes_size": 634880
      },
      "batch_proposer_config": {
        "propose_interval_milliseconds": 1000,
        "max_l1_commit_gas_per_batch": 5000000,
        "max_l1_commit_calldata_size_per_batch": 110000,
        "batch_timeout_sec": 2700,
        "gas_cost_increase_multiplier": 1.2,
        "max_uncompressed_batch_bytes_size": 634880
      },
      "bundle_proposer_config": {
        "max_batch_num_per_bundle": 30,
        "bundle_timeout_sec": 36000
      }
    },
    "db_config": {
      "driver_name": "postgres",
      "dsn": "",
      "maxOpenNum": 50,
      "maxIdleNum": 20
    }
  }
